doctrine_mongodb:
    connections:
        default:
            server: '%env(resolve:DATABASE_URL)%'
            options: {}
    default_database: nexof_db
    document_managers:
        default:
            database: nexof_db
            mappings:
                App:
                    type: attribute
                    is_bundle: false
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App